# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Analyze PowerShell

on:
  workflow_call:

jobs:
  analyze-powershell:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - name: Checkout the Actions repo
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846  # v3.0.0
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-Actions
          path: Ed-Fi-Actions

      - name: Checkout the repo to review
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846  # v3.0.0
        with:
          path: testing-repo

      - name: Analyze
        uses: ./Ed-Fi-Actions/powershell-analyzer
        id: powershell-analyzer
        with:
          directory: ./testing-repo/

      - name: Upload Result
        uses: github/codeql-action/upload-sarif@1fae5bf71b0ecdc7d0a2ef0d0c28409d99693966 #v2.9.2
        with:
          sarif_file: ./results.sarif
