# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Repo Security Scan
on:
  workflow_call:
    inputs:
      directory:
        description: The directory to scan
        required: false
        default: './'
        type: string
      recursive:
        description: True to scan all directories recursively
        required: false
        default: true
        type: boolean
      config-file-path:
        description: (Optional) path to additional config file in the destination repository
        required: false
        default: ''
        type: string

jobs:
  action-allowedlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Actions repo
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-Actions
          path: Ed-Fi-Actions

      - name: Checkout the repo to Scan
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          path: testing-repo

      - name: Scan used actions
        uses: ./Ed-Fi-Actions/action-allowedlist
        id: scan-action

  bidi-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Actions repo
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-Actions
          path: Ed-Fi-Actions

      - name: Checkout the repo to Scan
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          path: testing-repo

      - name: Echo input
        run: |
          echo 'Config file path: ${{ inputs.config-file-path }}'
          echo 'Directory: ${{ inputs.directory }}'
          echo 'Recursive: ${{ inputs.recursive }}'

      - name: Bidirectional Trojan source detector
        uses: ./Ed-Fi-Actions/bidi-scanner
        with:
            config-file-path: ${{ inputs.config-file-path }}
            directory: ./testing-repo/${{ inputs.directory }}
            recursive: ${{ inputs.recursive }}
